master_panel=
sidebarPanel(
  uiOutput("var")
  ,br()
  ,br()
  ,br()
  ,uiOutput("codsis")
  ,uiOutput("codlft")
  ,actionButton("reset", "Reset")
  ,br()
  ,br()
  ,br()
  ,uiOutput("strato")
  ,br()
  ,br()
  ,br()
  ,checkboxInput(inputId = "check_gio",label = "Fishing days>0", value=T)
  ,br()
  ,br()
  ,br()
  ,h5("Notes:")
  ,textOutput("perc_consegne_mensili")
  ,textOutput("perc_consegne_annuali")
)